title: Nexus Website
theme: jekyll-theme-slate

plugins:
  - jekyll-remote-theme

remote_theme: jekyll-ja/jekyll-theme-slate

#title: Nexus Website
#theme: minima

#plugins:
#  - jekyll-remote-theme

#remote_theme: just-the-docs/just-the-docs
