title: The Crimson Den

# Use Chirpy theme from GitHub Pages
remote_theme: cotes2020/jekyll-theme-chirpy

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

# Enable Dark Mode
theme_mode: dark
