title: Nexus Website
theme: jekyll-clean-dark

plugins:
  - jekyll-remote-theme

remote_theme: scotte/jekyll-clean-dark

#title: Nexus Website
#theme: minima

#plugins:
#  - jekyll-remote-theme

#remote_theme: just-the-docs/just-the-docs
