title: Nexus Website
description: >
  Welcome to my Nexus Website powered by Jekyll!
  
# Use the jekyll-dark-ored remote theme
remote_theme: son-link/jekyll-dark-ored

# Plugins required for remote themes
plugins:
  - jekyll-remote-theme

  home: index.md

#title: Nexus Website
#theme: minima

#plugins:
#  - jekyll-remote-theme

#remote_theme: just-the-docs/just-the-docs
