theme: jekyll-theme-minimal  # A clean and simple theme

plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/minimal

#title: Nexus Website
#theme: minima

#plugins:
#  - jekyll-remote-theme

#remote_theme: just-the-docs/just-the-docs
